import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { GameComponent } from './pages/game/game.component';
import { QuemSouEuComponent } from './pages/play/quem-sou-eu/quem-sou-eu.component';
import { ChaOuCafeComponent } from './pages/play/cha-ou-cafe/cha-ou-cafe.component';
import { ItoComponent } from './pages/play/ito/ito.component';
import { BatataQuenteComponent } from './pages/play/batata-quente/batata-quente.component';
import { PerguntaDoImpostorComponent } from './pages/play/pergunta-do-impostor/pergunta-do-impostor.component';
import { ContatoComponent } from './pages/play/contato/contato.component';
import { ImpostorComponent } from './pages/play/impostor/impostor.component';
import { AdivinheAPalavraComponent } from './pages/play/adivinhe-a-palavra/adivinhe-a-palavra.component';
import { QualEANotaComponent } from './pages/play/qual-e-a-nota/qual-e-a-nota.component';
import { JogoDaListaComponent } from './pages/play/jogo-da-lista/jogo-da-lista.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'game/:id', component: GameComponent },
  { path: 'play/quem-sou-eu', component: QuemSouEuComponent },
  { path: 'play/cha-ou-cafe', component: ChaOuCafeComponent },
  { path: 'play/ito', component: ItoComponent },
  { path: 'play/batata-quente', component: BatataQuenteComponent },
  { path: 'play/pergunta-do-impostor', component: PerguntaDoImpostorComponent },
  { path: 'play/contato', component: ContatoComponent },
  { path: 'play/impostor', component: ImpostorComponent },
  { path: 'play/adivinhe-a-palavra', component: AdivinheAPalavraComponent },
  { path: 'play/qual-e-a-nota', component: QualEANotaComponent },
  { path: 'play/jogo-da-lista', component: JogoDaListaComponent },
  { path: '**', redirectTo: '' }
];
